const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,current=null,authMode="login";
let state={mov:[],contas:[],orc:[],orcItens:[]};
let calDate=new Date(),selectedDate=null,calFilter="TODOS";
const $=id=>document.getElementById(id);
const brl=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const hoje=()=>new Date().toISOString().slice(0,10);
const dataBR=s=>{if(!s)return"";const[y,m,d]=s.split("-");return`${d}/${m}/${y}`};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const uid=()=>session?.user?.id;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const accountName=a=>a==="PF"?"Pessoa Física":"CNPJ";

function setAuth(m){authMode=m;$("tabLogin").classList.toggle("active",m==="login");$("tabSignup").classList.toggle("active",m==="signup");$("nomeWrap").classList.toggle("hidden",m!=="signup");$("authSubmit").textContent=m==="login"?"Entrar":"Criar conta";$("authMsg").textContent=""}
$("tabLogin").onclick=()=>setAuth("login");$("tabSignup").onclick=()=>setAuth("signup");
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="";try{const email=$("email").value.trim(),password=$("senha").value;if(authMode==="signup"){const nome=$("nome").value.trim();const {data,error}=await sb.auth.signUp({email,password,options:{data:{nome},emailRedirectTo:"https://pisonconect-droid.github.io/meu-financeiro/"}});if(error)throw error;if(data.session)await ensureProfile(data.user,nome);$("authMsg").style.color="#047857";$("authMsg").textContent=data.session?"Conta criada.":"Conta criada. Confirme seu e-mail e depois entre."}else{const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error}}catch(err){$("authMsg").style.color="#b91c1c";$("authMsg").textContent=err.message||"Erro ao autenticar."}};
async function ensureProfile(user,nome=""){if(user)await sb.from("profiles").upsert({id:user.id,nome:nome||user.user_metadata?.nome||""},{onConflict:"id"})}
$("logout").onclick=()=>sb.auth.signOut();
sb.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s?.user){await ensureProfile(s.user);showApp();await loadAll()}else showAuth()});
async function start(){const {data}=await sb.auth.getSession();session=data.session;if(session?.user){await ensureProfile(session.user);showApp();await loadAll()}else showAuth()}
function showAuth(){$("auth").classList.remove("hidden");$("app").classList.add("hidden")}
function showApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userEmail").textContent=session.user.email||"";goHome()}

async function loadAll(){const [m,c,o,oi]=await Promise.all([sb.from("movimentacoes").select("*").order("data",{ascending:false}).order("created_at",{ascending:false}),sb.from("contas").select("*").order("vencimento"),sb.from("orcamentos").select("*").order("created_at",{ascending:false}),sb.from("orcamento_itens").select("*")]);const er=m.error||c.error||o.error||oi.error;if(er){alert(er.message);return}state={mov:m.data||[],contas:c.data||[],orc:o.data||[],orcItens:oi.data||[]};render();renderCalendar()}

document.querySelectorAll("[data-account]").forEach(b=>b.onclick=()=>openArea(b.dataset.account));$("homeBtn").onclick=goHome;$("openCalendar").onclick=openCalendar;$("calendarToday").textContent=dataBR(hoje());
function setView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id))}
function goHome(){current=null;setView("home");$("homeBtn").classList.add("hidden");$("subtitle").textContent="Escolha uma área";render()}
function openArea(a){current=a;setView("area");$("homeBtn").classList.remove("hidden");$("accountName").textContent=accountName(a);$("subtitle").textContent=accountName(a);$("orcWrap").classList.toggle("hidden",a!=="CNPJ");render()}
function openCalendar(){current=null;setView("calendarView");$("homeBtn").classList.remove("hidden");$("subtitle").textContent="Calendário financeiro";renderCalendar()}

$("btnEntrada").onclick=()=>openMov("entrada");$("btnGasto").onclick=()=>openMov("saida");$("btnConta").onclick=()=>openConta();
function openMov(tipo,x=null){$("mode").value="mov";$("editId").value=x?.id||"";$("modalTitle").textContent=x?"Editar lançamento":tipo==="entrada"?"Nova entrada":"Novo gasto";$("descricao").value=x?.descricao||"";$("valor").value=x?.valor||"";$("data").value=x?.data||hoje();$("data").dataset.tipo=tipo;$("dateLabel").childNodes[0].nodeValue="Data ";$("modal").classList.remove("hidden")}
function openConta(x=null){$("mode").value="conta";$("editId").value=x?.id||"";$("modalTitle").textContent=x?"Editar conta":"Adicionar conta";$("descricao").value=x?.descricao||"";$("valor").value=x?.valor||"";$("data").value=x?.vencimento||hoje();$("dateLabel").childNodes[0].nodeValue="Vencimento ";$("modal").classList.remove("hidden")}
$("closeModal").onclick=()=>$("modal").classList.add("hidden");
$("modalForm").onsubmit=async e=>{e.preventDefault();const editing=$("editId").value;if($("mode").value==="mov"){const p={user_id:uid(),conta:current,tipo:$("data").dataset.tipo,descricao:$("descricao").value.trim(),valor:+$("valor").value,data:$("data").value,origem:"manual"};const q=editing?sb.from("movimentacoes").update(p).eq("id",editing):sb.from("movimentacoes").insert(p);const {error}=await q;if(error)return alert(error.message)}else{const p={user_id:uid(),conta:current,descricao:$("descricao").value.trim(),valor:+$("valor").value,vencimento:$("data").value};if(!editing)p.status="pendente";const q=editing?sb.from("contas").update(p).eq("id",editing):sb.from("contas").insert(p);const {error}=await q;if(error)return alert(error.message)}$("modal").classList.add("hidden");await loadAll()};

async function delMov(id){if(confirm("Excluir lançamento?")){const {error}=await sb.from("movimentacoes").delete().eq("id",id);if(error)alert(error.message);else loadAll()}}
async function delConta(id){if(confirm("Excluir conta?")){const {error}=await sb.from("contas").delete().eq("id",id);if(error)alert(error.message);else loadAll()}}
function editMov(id){const x=state.mov.find(x=>x.id===id);if(x)openMov(x.tipo,x)}
function editConta(id){const x=state.contas.find(x=>x.id===id);if(x)openConta(x)}
async function pagarConta(id){const x=state.contas.find(x=>x.id===id);if(!x)return;let {error}=await sb.from("contas").update({status:"pago",pago_em:hoje()}).eq("id",id);if(error)return alert(error.message);({error}=await sb.from("movimentacoes").insert({user_id:uid(),conta:x.conta,tipo:"saida",descricao:x.descricao,valor:x.valor,data:hoje(),origem:"conta_paga"}));if(error)return alert(error.message);await loadAll()}

$("btnTransfer").onclick=()=>{$("transferDirection").textContent=`${accountName(current)} → ${accountName(current==="PF"?"CNPJ":"PF")}`;$("transferDate").value=hoje();$("transferValue").value="";$("transferModal").classList.remove("hidden")};
$("closeTransfer").onclick=()=>$("transferModal").classList.add("hidden");
$("transferForm").onsubmit=async e=>{e.preventDefault();const destino=current==="PF"?"CNPJ":"PF";const {error}=await sb.rpc("transferir_valor",{p_origem:current,p_destino:destino,p_valor:+$("transferValue").value,p_descricao:$("transferDesc").value.trim()||"Transferência",p_data:$("transferDate").value});if(error)return alert("Transferência: "+error.message);$("transferModal").classList.add("hidden");await loadAll()};

function saldo(a){return state.mov.filter(x=>x.conta===a).reduce((s,x)=>s+(x.tipo==="entrada"?+x.valor:x.tipo==="saida"?-x.valor:0),0)}
const sum=a=>a.reduce((s,x)=>s+Number(x.valor),0);
function render(){$("saldoPF").textContent=brl(saldo("PF"));$("saldoCNPJ").textContent=brl(saldo("CNPJ"));if(!current)return;const s=saldo(current);$("saldoAtual").textContent=brl(s);$("saldoAtual").className=s>0?"positive":s<0?"negative":"";$("statusSaldo").textContent=s>0?"POSITIVO":s<0?"NEGATIVO":"ZERADO";$("movList").innerHTML=listMov(state.mov.filter(x=>x.conta===current));const h=hoje(),cs=state.contas.filter(x=>x.conta===current),late=cs.filter(x=>x.status==="pendente"&&x.vencimento<h),pay=cs.filter(x=>x.status==="pendente"&&x.vencimento>=h),paid=cs.filter(x=>x.status==="pago");$("tAtrasadas").textContent=brl(sum(late));$("tPagar").textContent=brl(sum(pay));$("tPagas").textContent=brl(sum(paid));$("atrasadas").innerHTML=listConta(late,true);$("pagar").innerHTML=listConta(pay,true);$("pagas").innerHTML=listConta(paid,false);if(current==="CNPJ")renderOrc()}
function listMov(a){return a.length?a.slice(0,50).map(x=>`<div class="item"><div><b>${esc(x.descricao)}</b><div class="meta">${dataBR(x.data)} · ${x.tipo==="entrada"?"Entrada":"Gasto"}${x.origem==="transferencia"?" · Transferência":""}</div></div><div><b class="${x.tipo==="entrada"?"positive":"negative"}">${x.tipo==="entrada"?"+":"-"} ${brl(x.valor)}</b><div class="actions"><button onclick="editMov('${x.id}')">Editar</button><button class="danger" onclick="delMov('${x.id}')">Excluir</button></div></div></div>`).join(""):`<p class="meta">Nenhum lançamento.</p>`}
function listConta(a,open){return a.length?a.map(x=>`<div class="item"><div><b>${esc(x.descricao)}</b><div class="meta">Vence ${dataBR(x.vencimento)}</div></div><div><b>${brl(x.valor)}</b><div class="actions">${open?`<button onclick="pagarConta('${x.id}')">Marcar paga</button><button onclick="editConta('${x.id}')">Editar</button>`:""}<button class="danger" onclick="delConta('${x.id}')">Excluir</button></div></div></div>`).join(""):`<p class="meta">Nenhuma conta.</p>`}

$("btnOrc").onclick=()=>{$("orcFormWrap").classList.remove("hidden");$("orcData").value=hoje();if(!$("orcItens").children.length)addOrcItem()};
$("cancelOrc").onclick=()=>{$("orcForm").reset();$("orcItens").innerHTML="";$("orcFormWrap").classList.add("hidden");calcOrc()};
$("addItem").onclick=addOrcItem;
function addOrcItem(){const f=$("budgetItemTemplate").content.cloneNode(true),r=f.querySelector(".budget-item-row");r.querySelectorAll("input,select").forEach(i=>i.oninput=calcOrc);r.querySelector(".remove-budget-item").onclick=()=>{r.remove();calcOrc()};$("orcItens").appendChild(f);calcOrc()}
function orcItems(){return[...document.querySelectorAll(".budget-item-row")].map(r=>({tipo:r.querySelector(".iTipo").value,descricao:r.querySelector(".iDesc").value.trim(),quantidade:+r.querySelector(".iQtd").value||0,valor_unitario:+r.querySelector(".iVal").value||0}))}
function calcOrc(){const its=orcItems(),pecas=its.filter(x=>x.tipo==="peca").reduce((s,x)=>s+x.quantidade*x.valor_unitario,0),mo=its.filter(x=>x.tipo==="mao_obra").reduce((s,x)=>s+x.quantidade*x.valor_unitario,0);$("totalPecas").textContent=brl(pecas);$("totalMO").textContent=brl(mo);$("orcTotal").textContent=brl(pecas+mo);return{pecas,mo,total:pecas+mo}}
$("orcForm").onsubmit=async e=>{e.preventDefault();const its=orcItems(),t=calcOrc();if(!its.length)return alert("Adicione pelo menos um item.");const {data:o,error}=await sb.from("orcamentos").insert({user_id:uid(),cliente:$("orcCliente").value.trim(),whatsapp:$("orcWhatsapp").value,data:$("orcData").value,descricao:$("orcDesc").value,total:t.total,subtotal_pecas:t.pecas,subtotal_mao_obra:t.mo,status:"orcamento"}).select().single();if(error)return alert(error.message);const rows=its.map(x=>({user_id:uid(),orcamento_id:o.id,...x}));const r=await sb.from("orcamento_itens").insert(rows);if(r.error)return alert(r.error.message);$("orcForm").reset();$("orcItens").innerHTML="";$("orcFormWrap").classList.add("hidden");await loadAll()};
async function aprovarOrc(id){const {error}=await sb.from("orcamentos").update({status:"aprovado"}).eq("id",id).eq("status","orcamento");if(error)alert(error.message);else loadAll()}
async function pagarOrc(id){if(!confirm("Confirmar pagamento? O valor entrará no saldo CNPJ."))return;const {error}=await sb.rpc("marcar_orcamento_pago",{p_orcamento_id:id,p_data:hoje()});if(error)alert("Pagamento: "+error.message);else loadAll()}
async function delOrc(id){const o=state.orc.find(x=>x.id===id);if(o?.status==="pago")return alert("Orçamento pago não pode ser excluído.");if(confirm("Excluir orçamento?")){const {error}=await sb.from("orcamentos").delete().eq("id",id);if(error)alert(error.message);else loadAll()}}
function renderOrc(){$("orcList").innerHTML=state.orc.length?state.orc.map(o=>{const its=state.orcItens.filter(x=>x.orcamento_id===o.id);return `<details class="item budget-record"><summary><div><b>Orçamento ${o.numero} · ${esc(o.cliente)}</b><div class="meta">${dataBR(o.data)}</div><span class="status-pill ${o.status}">${o.status==="orcamento"?"Orçamento":o.status==="aprovado"?"Aprovado":"Pago"}</span></div><b>${brl(o.total)}</b></summary><div class="budget-detail"><div class="budget-split"><span>Peças <b>${brl(o.subtotal_pecas)}</b></span><span>M.O. <b>${brl(o.subtotal_mao_obra)}</b></span></div>${its.map(i=>`<div class="meta">${i.tipo==="peca"?"Peça":"M.O."}: ${esc(i.descricao)} · ${i.quantidade} × ${brl(i.valor_unitario)}</div>`).join("")}<div class="actions">${o.status==="orcamento"?`<button class="warning" onclick="aprovarOrc('${o.id}')">Aprovar</button>`:""}${o.status==="aprovado"?`<button class="success" onclick="pagarOrc('${o.id}')">Marcar pago</button>`:""}${o.status!=="pago"?`<button class="danger" onclick="delOrc('${o.id}')">Excluir</button>`:""}</div></div></details>`}).join(""):`<p class="meta">Nenhum orçamento.</p>`}

$("prevMonth").onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);renderCalendar()};
$("nextMonth").onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);renderCalendar()};
document.querySelectorAll("[data-cal-filter]").forEach(b=>b.onclick=()=>{calFilter=b.dataset.calFilter;document.querySelectorAll("[data-cal-filter]").forEach(x=>x.classList.toggle("active",x===b));renderCalendar()});
function calEvents(date){const ok=a=>calFilter==="TODOS"||a===calFilter,events=[];state.mov.filter(x=>x.data===date&&ok(x.conta)).forEach(x=>events.push({type:"mov",title:x.descricao,meta:`${accountName(x.conta)} · ${x.tipo==="entrada"?"Entrada":"Gasto"} · ${brl(x.valor)}`}));state.contas.filter(x=>x.vencimento===date&&ok(x.conta)).forEach(x=>events.push({type:"bill",title:x.descricao,meta:`${accountName(x.conta)} · ${x.status==="pago"?"Paga":"Vencimento"} · ${brl(x.valor)}`}));if(calFilter==="TODOS"||calFilter==="CNPJ")state.orc.filter(x=>x.data===date).forEach(x=>events.push({type:"orc",title:`Orçamento ${x.numero} · ${x.cliente}`,meta:`CNPJ · ${x.status} · ${brl(x.total)}`}));return events}
function renderCalendar(){if(!$("calendarGrid"))return;const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1);$("monthTitle").textContent=first.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});const start=new Date(y,m,1-first.getDay()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=iso(d),ev=calEvents(ds);cells.push(`<button class="day ${d.getMonth()!==m?"other":""} ${ds===hoje()?"today":""} ${ds===selectedDate?"selected":""}" data-date="${ds}" type="button"><span class="num">${d.getDate()}</span><span class="dots">${[...new Set(ev.map(e=>e.type))].map(t=>`<i class="dot ${t}"></i>`).join("")}</span></button>`)}$("calendarGrid").innerHTML=cells.join("");document.querySelectorAll(".day").forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar();renderSelectedDate()});if(selectedDate)renderSelectedDate()}
function renderSelectedDate(){$("selectedDateTitle").textContent=dataBR(selectedDate);const ev=calEvents(selectedDate);$("calendarEvents").innerHTML=ev.length?ev.map(e=>`<div class="event ${e.type}"><b>${esc(e.title)}</b><div class="meta">${esc(e.meta)}</div></div>`).join(""):`<p class="meta">Nenhum lançamento ou vencimento neste dia.</p>`}

window.delMov=delMov;window.delConta=delConta;window.editMov=editMov;window.editConta=editConta;window.pagarConta=pagarConta;window.aprovarOrc=aprovarOrc;window.pagarOrc=pagarOrc;window.delOrc=delOrc;
start();